### ISSUE TITLE
Incorrect positionning on multi-screen setup

### ISSUE THREAD

**Issue by Akryum** [icedman/search-light#1]
The window doesn't display on the main screen and is not center on the screen it chooses.

Here the center screen is the primary one:

![Screenshot from 2022-11-03 14-44-07](https://user-images.githubusercontent.com/2798204/199737120-f81b143c-d407-4b9e-9704-e5279865d6e4.png)

![image](https://user-images.githubusercontent.com/2798204/199737973-1b44002d-6c4b-4dd6-8820-b14151934e0a.png)

**Comment by AlexTheZoomer** [comment]
Yep! Same issue here on Fedora 36

**Comment by icedman** [comment]
Should be fixed now with release 3.

**Comment by IanTrudel** [comment]
> Should be fixed now with release 3.

It only appears on the middle screen (out of 3) at the moment rather than the screen where the mouse cursor is. Might also need testing on 4+ monitors.

**Comment by icedman** [comment]
You can choose a preferred monitor on the settings. Tested only with two monitors though.

**Comment by icedman** [comment]
Follow cursor is a good idea.
