### ISSUE TITLE
Big icons (Hi Res monitor)

### ISSUE THREAD

**Issue by brunnogama** [icedman/search-light#10]
Hi,
Icons are so big on my 2.5k monitor.
Is there a way to resize?

Thanx!

**Comment by icedman** [comment]
Could you give a screenshot? Thanks.

**Comment by brunnogama** [comment]
Here.
Thanx for your great work, btw.

![Captura de tela de 2022-11-05 11-03-10](https://user-images.githubusercontent.com/30611127/200123731-66df9c59-39aa-4e65-9d53-653d618f9668.png)

**Comment by icedman** [comment]
Hey you have the High Sierra background :) 
Checkout https://github.com/icedman/dash2dock-lite
It is an animated dock like the macOS. You might want to test it and help me improve it as well.
Thanks/
