### ISSUE TITLE
[BUG] Doesn't display on top of full screen videos from Firefox (tested with Youtube) and MPV

### ISSUE THREAD

**Issue by VarLad** [icedman/search-light#11]
It does display for a split second when I type (searching stuff)

**Comment by icedman** [comment]
Fixed. This needs testing. On chrome-youtube (arch linux, vanilla gnome 43) this works fine.

**Comment by VarLad** [comment]
@icedman Doesn't work for me in Firefox or MPV
Can confirm to work on Chromium though
