### ISSUE TITLE
 [BUG] Esc to close doesn't work when something is selected

### ISSUE THREAD

**Issue by VarLad** [icedman/search-light#13]
After I type a name and use Arrow keys/tab to select something, I can't close the search using the Escape button.
What does work is, using mouse or Super key to focus back on search bar. Then I can use Escape to close the search
Might be related to https://github.com/icedman/search-light/issues/12

**Comment by icedman** [comment]
This has been address in latest release. I pushed it in EGO right away - still needs testing.

**Comment by VarLad** [comment]
I wonder how long does it take to hit extensions.gnome.org after being pushed :smile

**Comment by VarLad** [comment]
After updating to the newest release:

Its not perfect but better than what it was. Now after selecting something with tab and arrow key, and typing to search further, the first key press redirects the selection to the first option in the search. After that you can type whatever you want
Same for Escape key to close. The first time I press the escape key, it redirects the selection to the first selection result (given that I've selected something else using the arrow key or tab) 

The desirable behavior would be to not redirect the selection to the first search result on the first key press

**Comment by icedman** [comment]
r4. After typing, and moving the selection down - the text input loses focus. Typing (including pressing escape) refocuses the text input. Will improve further.
