### ISSUE TITLE
doesn't close/disappear on ''submit''

### ISSUE THREAD

**Issue by cassop** [icedman/search-light#15]
After typing and selecting (let say firefox or anything) it should instantly disappear or close itself, but it waits until the selected stuff opens.

**Comment by VarLad** [comment]
This could even be a design choice. 
Since that way it'll only close when something actually opens.

**Comment by icedman** [comment]
This is the expected behavior.
Other items like 'copy to clipboard' when you do math wouldn't close the popup when selected.

**Comment by ColiZei** [comment]
@icedman Thanks for this cool extension!

> After typing and selecting (let say firefox or anything) it should instantly disappear or close itself, but it waits until the selected stuff opens.

I agree with this. On Gnome search it instantly disappear on "submit".

If you hit enter or click on a item and nothing happens for a time is not a good experience.
Especially if you open a large application.
"Did it work? Dit it open?".. waiting.

Alternatively you can add a loading inicator or anything else?

**Comment by cassop** [comment]
It's not noticeable for most of apps except for the big ones..
> If you hit enter or click on a item and nothing happens for a time is not a good experience.

Exactly.... it even gets a bit annoying when the program has splash or so....
[Screencast from 2022-11-07 20-57-17.webm](https://user-images.githubusercontent.com/92434806/200384108-343bc59c-a23e-4c56-a087-9e140957018e.webm)
 take GIMP as an example...

**Comment by icedman** [comment]
Acknowledged and I agree. I will update accordingly.
