### ISSUE TITLE
Icon flinks 

### ISSUE THREAD

**Issue by rqy2002** [icedman/search-light#16]
https://user-images.githubusercontent.com/22741844/200243074-678eeb9a-0338-4ffb-a6bd-4decd01014b4.mp4

I don't know why.

**Comment by icedman** [comment]
I could not reproduce. Could you tell me: your screen size and scaling. And the values for your extension width/height. Thanks

**Comment by icedman** [comment]
A lot of changes already - including icons shaking. Please re-file if there is still this issue.
