### ISSUE TITLE
[Feature request] Enable mouse scroll

### ISSUE THREAD

**Issue by sekurilabs** [icedman/search-light#18]
A nice feature on extension would be to enable mouse scroll on the search results because most of the times it's faster to get to a result than using arrow key.

 Also when dragging the scroll bar to bottom it automatically bounces back to the top (initial position).

**Comment by icedman** [comment]
This is confirmed and acknowledge. I still haven't found a way to fix this bug. This is in X11 only.
On Wayland, touchpad scrolling works. I think so would mouse scroll.

**Comment by kugelvlitz** [comment]
> On Wayland, touchpad scrolling works. I think so would mouse scroll.
 
I'm on Wayland, mouse scrolling doesn't seem to work, it just scrolls the window behind the search bar. If I click and drag it works though, but not ideal.

**Comment by icedman** [comment]
Added with Release 6.
