### ISSUE TITLE
Keybinding - does not trigger

### ISSUE THREAD

**Issue by martinlindelof** [icedman/search-light#19]
![image](https://user-images.githubusercontent.com/156772/200709722-314ade81-768b-4cd2-a53b-9002f1926bce.png)
After updating to V4 and logout, search light won't trigger. Tried to reset keyboard shortcut to default ctrl+alt+space but not working.

**Comment by icedman** [comment]
Could you tell me your system. And would you be able to get the logs ```journalctl -f ..` when you enable/disable the extension.

**Comment by martinlindelof** [comment]
Linux based 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

OS: Ubuntu 22.10 x86_64 

> JS WARNING: [/home/martin/.local/share/gnome-shell/extensions/search-light@icedman.github.com/extension.js 323]: unreachable code after return statement

**Comment by icedman** [comment]
Line 323 merley pertains to disabled code for the requested blurring background feature. 

I do test on Ubuntu 22.10 (and arch Linux). So far, I couldn't  reproduce. Any more info would be appreciated.

**Comment by martinlindelof** [comment]
I have blur my shell 44 extension installed, will dig more info later if possible and post here.
