### ISSUE TITLE
Can't scroll with mouse wheel

### ISSUE THREAD

**Issue by Akryum** [icedman/search-light#2]
I can't scroll using my mouse wheel in the result window

**Comment by icedman** [comment]
Note: if a scrollable window is below the search box, mouse wheel doesn't work.

**Comment by brunnogama** [comment]
Same here, with touchpad.

**Comment by icedman** [comment]
Note: Wayland has no such problem.

**Comment by icedman** [comment]
Should be fixed with latest commit
