### ISSUE TITLE
Search Light breaks GNOME Activities search box

### ISSUE THREAD

**Issue by someAdityaSingh** [icedman/search-light#20]
After using Search Light, the search box in GNOME Activities looks like this:

![Screenshot from 2022-11-13 10-27-45](https://user-images.githubusercontent.com/80509675/201506635-912e18d9-24b1-4fa2-8ad8-75338ebd82a8.png)

Also, the text is not aligned in Search Light:

![Screenshot from 2022-11-13 10-32-43](https://user-images.githubusercontent.com/80509675/201506669-f4e529d4-5db4-4762-90e7-518a427eb402.png)

Running the latest code git cloned at 2022-11-13 10:26:10.495287809 +0530.

**Comment by icedman** [comment]
Please check latest release (5) which fixes this issue.

**Comment by someAdityaSingh** [comment]
Yes, it is fixed.

**Comment by someAdityaSingh** [comment]
Yes, it is fixed.
