### ISSUE TITLE
[Feature request] Add margin to scrollbar so not to overlap result widgets

### ISSUE THREAD

**Issue by kugelvlitz** [icedman/search-light#21]
Unless a width larger than the result "widgets" (see picture) max width is given, the scrollbar on the right will overlap with it. Some margin would be ideal to keep a more clean and organized look.
![Screenshot from 2022-11-13 17-48-53](https://user-images.githubusercontent.com/20900242/201551215-578ac7e2-214a-4221-8c79-9773cd4b8a11.png)

**Comment by icedman** [comment]
Added with Release 6. Please check it this improves the layout.

**Comment by kugelvlitz** [comment]
@icedman Although it does appear improved, there still seems to bit of overlap

![Screenshot from 2022-11-24 13-27-10](https://user-images.githubusercontent.com/20900242/203854274-93e0e2a3-d1ea-410c-826a-3f14d6ba5d52.png)

**Comment by icedman** [comment]
I added a little bit more padding.
