### ISSUE TITLE
Some key combinations are not recognized

### ISSUE THREAD

**Issue by olosegres** [icedman/search-light#24]
I try to bind Ctrl + Space as keyboard shortcut, but when I press it - nothing happens (app does not see that I press). 
But for example if I press Ctrl+M - it works as expected.

Is there way to set desired combination via config? 
Or may be some thoughts about causes of the problem?

Ubuntu 22.04

**Comment by icedman** [comment]
Some key combinations are probably reserved by the gnome shell or used by some other extension already.
```journalctl -f ``` at the terminal will mostly likely print out 'unable to grab CTRL+<Space>. I will look for a way to show error messages at the preference window.

**Comment by martinlindelof** [comment]
I usually just have ALT+ENTER for whatever terminal I am using.
And ALT+SHIFT+ENTER for App Launcher. But can't use ALT+SHIFT+ENTER for Search Light.

**Comment by icedman** [comment]
Please try other key combinations. Try three keys combination like this: Ctrl+Super+/
