### ISSUE TITLE
[Minor Bug] Stays At "Searching..." Mode

### ISSUE THREAD

**Issue by SercanDmr** [icedman/search-light#35]
1 - Search Something.

2 - Press "CTRL + A" And Delete Search Text.When You Type And Delete Fastly Similar Things Happening.Also If You Type And Delete Fastly Still Showing Result About Deleted Text.

3 - Stays At "Searching..." Mode -> Expected Result -> "No results."

**Comment by icedman** [comment]
@SercanDmr do you still experience this? I could not re-create this. Perhaps because I test on a slow 2017 laptop :)
