### ISSUE TITLE
Bug: Typelib file for namespace 'Adw' (any version) not found

### ISSUE THREAD

**Issue by Arkady-Dymkov** [icedman/search-light#42]
Error: Requiring Adw, version none: Typelib file for namespace 'Adw' (any version) not found

Stack trace:
  @/home/arkady/.local/share/gnome-shell/extensions/search-light@icedman.github.com/prefs.js:3:54
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by icedman** [comment]
The main branch version now requires gnome 45.
For g44 branch, please use gnome 42 or higher.
