### ISSUE TITLE
Add support for GNOME 44

### ISSUE THREAD

**Issue by VarLad** [icedman/search-light#43]
GNOME 44 is here! Would be nice to have this plugin there as well

**Comment by icedman** [comment]
I added Gnome 44 on the main branch. If people would confirm it is working fine, I would update the extension on the gnome site.

I don't have any Gnome 44 installion yet.

**Comment by tim-hm** [comment]
Tested on lunar lobster using the main branch. Working for me here!

**Comment by VarLad** [comment]
@icedman Can confirm it to be working as well

**Comment by iskigow** [comment]
Tested on openSUSE Tumbleweed using the main branch. Working for me too!!
![image](https://user-images.githubusercontent.com/30843/232341828-4eb358c4-0ecd-44e2-920c-3dab0ef9ffd3.png)

**Comment by andrepg** [comment]
Well, the commit [c5b66c05](https://github.com/icedman/search-light/commit/c5b66c05f65c751398e74941e3b0a6b560e3260b) added the 44 shell as accepted. But at this day, the gnome-shell page still hasn't the update library yet, right?

Just to know if I can wait, or it's better to build from source. Seems like a really lovable project.

**Comment by icedman** [comment]
For Gnome 44 and below .Please use g44 branch. Otherwise please update to Gnome 45 and the latest search-light version. Thanks.
