### ISSUE TITLE
Command for activating search-light

### ISSUE THREAD

**Issue by ghost** [icedman/search-light#50]
Hello,

I'd like to bind search light to just my Super button, using the Super Key extension https://github.com/Tommimon/super-key. What command should I use?

**Comment by vrmaurice** [comment]
Yes I really want this too, please someone help

**Comment by pathmann** [comment]
You need to remove the binding to gnomes application overlay first, see my comment in #23

**Comment by icedman** [comment]
I assume this has been solved. Sorry for the late reply. Please reopen if the bug persists. I added a "Bug Reporting" section on README which would be helpful to me. Thanks.
