### ISSUE TITLE
Squared corners

### ISSUE THREAD

**Issue by RustLover2910** [icedman/search-light#51]
I think there is something wrong with the extension, for some reason the corners are not rounded.
![Screenshot from 2023-05-28 21-11-44](https://github.com/icedman/search-light/assets/120085236/a9595c80-dddc-4f61-9538-dff9228f4ff3)
I am on fedora 38 and the extension version is gnome 44 and extension ver 12

**Comment by vrmaurice** [comment]
You can change the radius of the corners in the extensions settings. Under Appearance > Border Radius

**Comment by RustLover2910** [comment]
Thanks mate
