### ISSUE TITLE
Don't display text on first startup

### ISSUE THREAD

**Issue by nkcong206** [icedman/search-light#52]
When I just config or related to reset, the text and icon are hidden.

![Screenshot from 2023-06-05 20-32-00](https://github.com/icedman/search-light/assets/56025592/caf2b2c0-462c-4fb3-b9d9-9ae61228b9be)

**Comment by vivantart** [comment]
+1

**Comment by eloymelo** [comment]
Same issue here. Fedora 39

**Comment by icedman** [comment]
I think I fixed this already and wasn't able to update this issue. Please reopen if this persist. I haven't seen this in Gnome 45, Gnome 46.
