### ISSUE TITLE
Keybindings not trigger on wayland when app window is maximized

### ISSUE THREAD

**Issue by oodzchen** [icedman/search-light#53]
I've update GNOME 44 on Manjaro, and use Wayland. And I set the Search Light keybindings as `Super + S`, when the window of focus app is maximized, the keyboard shortcut of this extension not working, but the system keyboard shortcuts works fine.

BYW: When I login GNOME in Xorg mode, everything works fine.

**Comment by icedman** [comment]
Solution has been found and fix uploaded see #77
