### ISSUE TITLE
[Bug] Pink border instead of transparent

### ISSUE THREAD

**Issue by benlc** [icedman/search-light#55]
I'm on Fedora 37, Gnome 44, Wayland+Nvidia.

Everything's been working just fine for several months. I updated some packages today and after restarting I'm getting a pink border around search light instead of being properly transparent. I tried reinstalling and tinkering a bit with appearance settings but can't seem to get it to go away. Not sure if anyone else is experiencing this

![image](https://github.com/icedman/search-light/assets/1082345/bf5d6077-e3dd-49a0-bd2a-87ef2e6d207d)
![image](https://github.com/icedman/search-light/assets/1082345/e53761e8-c126-4f8a-8c43-d6e6a84b29d2)

**Comment by icedman** [comment]
Yes, also in vanilla gnome 44, arch Linux.  That is what's frustrating with gnome. At every release, somethings aways break. Disable blurring for now.

**Comment by benlc** [comment]
Got it that worked thanks @icedman !
