### ISSUE TITLE
Use the META key to activate

### ISSUE THREAD

**Issue by LeonardoLeite** [icedman/search-light#58]
Is there a way to use the META key as one of the key combination to the keybindings?
No mater what I do, can't use it as one of the activation keys to Search box.

**Comment by icedman** [comment]
META is currently being used by the System to show the Overview.  I'm not inclined to override this at the moment. -- I thought about it but decided against it.

**Comment by icedman** [comment]
Sorry - I misunderstood.  You mean META (being the Windows(logo) key or the Command key in Macos) plus some other key combination?

Please indicate your system and gnome version. Thanks. Stack trace if possible. Please "Bug Reporting" on README.

**Comment by icedman** [comment]
Try Meta+Enter or Meta+/ .. I have this as my own keys.
Meta ... is the super key, or the Windows logo, or the Cmd key in MacOS
