### ISSUE TITLE
Extension disables super button

### ISSUE THREAD

**Issue by sekurilabs** [icedman/search-light#6]
Extension for some reason disables the Super button on the keyboard and I'm unable to go to overview unless I run the extension first (ctrl + super + space).

**Comment by KristianOde** [comment]
Same issue here, I can only enter overview exactly once each time I open and close this (search-light) menu.

**Comment by dahumph** [comment]
Same here, running ubuntu 22.04.1

**Comment by 1r0n-ZA** [comment]
Same problem. It also seems to disable the hot corner on Gnome 42.4 Fedora 36 (Wayland).
Tested in Xorg as well same issue, 
Nice extension though thanks.

**Comment by icedman** [comment]
Fixed.
Hot corners, not yet.

**Comment by 1r0n-ZA** [comment]
Hi

I tested today.
Hot corners are working and my super key still works. Thanks
