### ISSUE TITLE
Shortcut bug

### ISSUE THREAD

**Issue by Dathasai1234** [icedman/search-light#60]
not able to change the shortcut

**Comment by gramms** [comment]
It seems as if you can only pick shortcuts that haven't been assingned to something else in your system. Unfortunately Search Light will just do nothing if you try to re-assign a certain key combination.

I only found this out by trial and error.

**Comment by icedman** [comment]
There is still no way for the extension to tell if a shortcut is currently being used by the system and is unavailable.
I did add an improvement where the "Press shortcut keys..." message will remain visible until a valid shortcut is found. Or until escape (to cancel), or delete (to erase current shortcut) is pressed.

**Comment by mmartinortiz** [comment]
Do you think that will also be helpful if the message includes something like "The shortcut must be available. In case it is already assigned it will not be registered". If not in the pop-up, maybe in the "Keybindings" setting's section
