### ISSUE TITLE
Error opening preferences

### ISSUE THREAD

**Issue by CodedNil** [icedman/search-light#62]
When I click settings for the extension I am immediately shown somethings gone wrong with the below error message
Theres three tabs at the top, appearance works, the one after that displays nothing and has no label and a blank page icon, then third is the same but its the default and shows this error

TypeError: headerbar.pack_start is not a function

Stack trace:
  addMenu@/home/dan/.local/share/gnome-shell/extensions/search-light@icedman.github.com/prefs.js:39:13
  fillPreferencesWindow@/home/dan/.local/share/gnome-shell/extensions/search-light@icedman.github.com/prefs.js:94:10
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by icedman** [comment]
The main branch is now ported to Gnome 45. Please use g44 branch if you're not yet on Gnome 45.

**Comment by CodedNil** [comment]
I installed this on gnome 44 from the extensions app, it doesn't give me an option to choose which gnome version to install so I assume it would auto pick the gnome 44 version, should I install it manually from github instead?

**Comment by icedman** [comment]
I've uploaded to the Releases section of this github page.

https://github.com/icedman/search-light/releases
