### ISSUE TITLE
Not working in Gnome 45

### ISSUE THREAD

**Issue by momoRaza** [icedman/search-light#64]
I'm getting the following error when I updated the extensions in Fedora Gnome 45

Unable to load file from: file:///home/momo/.local/share/gnome-shell/extensions/search-light@icedman.github.com/plugins/units/convert.js (Error opening file /home/momo/.local/share/gnome-shell/extensions/search-light@icedman.github.com/plugins/units/convert.js: No such file or directory)

**Comment by icedman** [comment]
Could you confirm that you have the latest search-light version? (search-light 16 is for gnome 45)

**Comment by rickdkk** [comment]
I have a similar error. It worked some times after I went to the Fedora 39 beta, so not sure what triggers it.

![search-light-error](https://github.com/icedman/search-light/assets/33315062/f5ccf4c3-850d-4008-af9a-cf7c5d118894)

**Comment by momoRaza** [comment]
> Could you confirm that you have the latest search-light version? (search-light 16 is for gnome 45)

![image](https://github.com/icedman/search-light/assets/80984581/c9c5c672-9454-4e19-87a3-e2ff7a0171a8)

**Comment by iskigow** [comment]
Not working also on openSUSE Tumbleweed (20230922-0)

![image](https://github.com/icedman/search-light/assets/30843/810700cf-d7a4-4a40-91c7-36e37ec2fd3a)

**Comment by muhammad-ans** [comment]
Also not working on fedora silverblue 39 prerelease with stable gnome 45.
Same error

**Comment by snirt** [comment]
same here with the same error - openSUSE Tumbleweed
`Unable to load file from: file:///home/my-user/.local/share/gnome-shell/extensions/search-light@icedman.github.com/plugins/units/convert.js (Error opening file /home/my-user/.local/share/gnome-shell/extensions/search-light@icedman.github.com/plugins/units/convert.js: No such file or directory)`

it already worked under Gnome 45 and suddenly stopped.

**Comment by alexispurslane** [comment]
I'm now also getting this error (openSUSE Tumbleweed, updated my whole system just this morning): `Unable to load file from: file:///home/alexispurslane/.local/share/gnome-shell/extensions/search-light@icedman.github.com/plugins/units/convert.js (Error opening file /home/alexispurslane/.local/share/gnome-shell/extensions/search-light@icedman.github.com/plugins/units/convert.js: No such file or directory)`

**Comment by icedman** [comment]
I've uploaded version 18 to remove import of unused files.

**Comment by yochananmarqos** [comment]
It seems the previously reported issues are resolved with the latest commit. However,  I cannot actually trigger it via keyboard shortcuts. 

It seems rather odd the default doesn't appear in the Settings:

![image](https://github.com/icedman/search-light/assets/5437803/333e0abd-968e-48e2-9e9b-6f44ac819fcd)

What, pray tell is _ctrl+cmd+space_? This is GNU / Linux, not Mac. I tried using Super and Alt instead of whatever _cmd_ is to no avail. I also tried setting a custom keybinding like Ctrl+Super+/, but nothing happens.

**Comment by gander-code** [comment]
Custom keybinding broken for me also. Ctrl + Super + Space is a little un-intuitive for me, I'd like to at least set it to Super + Space if I can't have it override gnome overview shortcut. I can set it in the extension settings but it has no effect.

**Comment by gremo** [comment]
Key binding not working also for me, Fedora 39. Any chance to get back to work with cmd + space?

**Comment by rickdkk** [comment]
Just wanna chime in that the key binding I set (super + /) still works on Fedora 39 after upgrading, so it might be for new keybindings only(?).

**Comment by renataogarcia** [comment]
@rickdkk I´d think so, because I used dconf-editor to set the value directly and it also works.

**Comment by clevrf0x** [comment]
Shortcut not working on GNOME 45.3 Endeavour OS

**Comment by icedman** [comment]
Click the "new accelerator". That actually is a button.

**Comment by icedman** [comment]
The latest upload at EGO to fix Gnome 45 and Gnome 46. Please file a separate bug if the keyboard shortcut is problematic for you. Thanks!
