### ISSUE TITLE
Feature Request: Multiple Keybinds

### ISSUE THREAD

**Issue by Hyperspeed1313** [icedman/search-light#69]
From the same context as #68, I would like to bind both Super_L and Super_R to Search Light, but I'm currently only able to have one bound at a time. It would be nice if this extension supported multiple keybinds. I'm not sure if supporting an arbitrary number of keybinds is possible or as easy as supporting a fixed number of keybinds, but two is all I would need to bind both Super keys at the same time.

**Comment by beeaniebee** [comment]
agreed this would be a great option

**Comment by icedman** [comment]
Will look into this. Thanks for the suggestion.

**Comment by icedman** [comment]
Closing... It will be included on the next EGO release. The feature is there already on the development branch.
