### ISSUE TITLE
search-light not working with pop-shell 

### ISSUE THREAD

**Issue by Avijneyam** [icedman/search-light#7]
Here is how to check 

install pop-shell and activate that open any windows 
eg:- terminal, browser, file manager anything 
so pop-shell will auto maximize that now if you will try to open search-light it will not open but when you close that previously opened windows
and try to open search-light it will be open without any issue

**Comment by icedman** [comment]
Could you show logs when running the extension:
```sh
journalctl -f -o cat /usr/bin/gnome-shell
```
Thanks.

**Comment by Avijneyam** [comment]
```
Ignoring length property that isn't a number at line 1, col 50
Ignoring length property that isn't a number at line 1, col 31
Ignoring length property that isn't a number at line 21, col 17
Ignoring length property that isn't a number at line 22, col 18
Ignoring length property that isn't a number at line 21, col 17
Ignoring length property that isn't a number at line 22, col 18
Ignoring length property that isn't a number at line 21, col 17
Ignoring length property that isn't a number at line 22, col 18
Window manager warning: Property WM_NAME on window 0x280003e contained invalid UTF-8
Window manager warning: Property WM_NAME on window 0x280003e contained invalid UTF-8
Window manager warning: Property WM_NAME on window 0x280003e contained invalid UTF-8
#################################################
# after when point out my cursor on 2nd monitor search-light worked but not working in active monitor
#################################################
115
115
100
100
115
115
100
100
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Terminal/SearchProvider”
65288
65288
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Terminal/SearchProvider”
65288
65288
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Terminal/SearchProvider”
65288
65288
65288
65288
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Terminal/SearchProvider”
65288
65288
65288
65288
```

**Comment by Avijneyam** [comment]
```
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/gnome/Terminal/SearchProvider”
65288
65288
65288
65288
JS ERROR: TypeError: Soup.SessionAsync is not a constructor
getRequest/<@/root/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/utils.js:55:24
getRequest@/root/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/utils.js:54:12
_saveImage@/root/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:630:54
_playerPropsChanged@/root/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:237:26

JS ERROR: TypeError: Main._searchLight._search is null
_compute_size@/root/.local/share/gnome-shell/extensions/search-light@icedman.github.com/extension.js:265:5
show/<@/root/.local/share/gnome-shell/extensions/search-light@icedman.github.com/extension.js:283:14
runSequence@/root/.local/share/gnome-shell/extensions/search-light@icedman.github.com/utils.js:97:5
runSequence/seq._timeoutId<@/root/.local/share/gnome-shell/extensions/search-light@icedman.github.com/utils.js:103:16
wrappedFunc@/root/.local/share/gnome-shell/extensions/search-light@icedman.github.com/utils.js:39:10


Window manager warning: last_focus_time (3990930) is greater than comparison timestamp (3990929).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: last_user_time (3990930) is greater than comparison timestamp (3990929).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: 0x280003e appears to be one of the offending windows with a timestamp of 3990930.  Working around...
```

**Comment by rachit1601** [comment]
its working fine for me

**Comment by LucasRoesler** [comment]
I am having the same/similar issue. 

If I toggle Search Light off and then on, then in an empty workspace I can activate Search Light.

Next, I open an application with tiling mode activated, search light will not open. In fact, i can not get it to open again without toggling it off and then on. 

I suspect that this is actually a bug in tiling mode for pop-shell because when i disable tiling and then toggle Search Light, it works 100% as expected. 

I tried to use `journalctl` to debug, but there is _nothing_ in the logs. It is as if nothing happens at all. I am not very familiar with how to debug gnome shell extensions, so any advice for next steps would be appreciated. 

My naive idea right now is that pop-shell needs to add an exception for the Shell Light window, but the built in mechanism for adding custom exceptions requires clicking a button and then using the mouse to select the window in the overview, needless to say, this doesn't work with Search Light because as soon as you try to click the button, Search Light is dismissed, so there is no window to select. If i could figure out how to track the name/id of the Search Light window, then I would be willing to experiment with pop-shell and manually add the exception.

**Comment by icedman** [comment]
> I suspect that this is actually a bug in tiling mode for pop-shell because when i disable tiling and then toggle Search Light, it works 100% as expected.

This could be the cause.

**Comment by LucasRoesler** [comment]
@icedman this has started working consistently for me with Tiling mode activated in PopShell, when I updated to version 11 today. 

The only other thing that I changed is that I am in a Wayland session while testing it, I was using Xorg previously.

**Comment by arturbosch** [comment]
> @icedman this has started working consistently for me with Tiling mode activated in PopShell, when I updated to version 11 today.
> 
> The only other thing that I changed is that I am in a Wayland session while testing it, I was using Xorg previously.

I can confirm that it does work on wayland but does not work on x11 when at least 1 application is open.
If the workspace does not contain an application search-light is triggered.

**Comment by icedman** [comment]
I will probably install popOS to test for compatibility. As well as Fedora.

**Comment by cspipaon** [comment]
> > 
> 
> > > @icedman this has started working consistently for me with Tiling mode activated in PopShell, when I updated to version 11 today.
> > > The only other thing that I changed is that I am in a Wayland session while testing it, I was using Xorg previously.
> > 
> > 
> > I can confirm that it does work on wayland but does not work on x11 when at least 1 application is open. If the workspace does not contain an application search-light is triggered.
> 
> I have a multi-monitor setup using X11 with Tiling Mode activated in PopShell. It works if the monitor that I am launching search-light on does not have the focused application. So I can have applications open on the monitor where I want to launch search-light, they just can't be focused. Also not seeing any logs in `journalctl`.

Same behaviour as @bigolu on my machine.

**Comment by maxime-bern** [comment]
Hello, did someone find a workaround or a fix ?
I have the same problem on OpenSuze Tumbleweed (Gnome 44)

**Comment by Hekel1989** [comment]
Maybe not the solutions you guys are looking for, but Search Light does work very well with Forge (auto tiling, extremely similar to PopOs').

**Comment by vijay-prema** [comment]
> 

Great suggestion, I'm trying this out now and so far it works well.

**Comment by icedman** [comment]
```JS ERROR: TypeError: Main._searchLight._search is null```

This error (in Gnome 46) has been fixed. Please reopen if still persists.
