### ISSUE TITLE
TypeError: headerbar.pack_start is not a function

### ISSUE THREAD

**Issue by oyedejioyewole** [icedman/search-light#72]
Hey, I recently installed this plugin on my laptop running GNOME 44.5. The plugin installation was smooth, but when I opened the settings using `Extension Manager` and `Extensions`, I got this error (screenshot will be provided below it):

```log
TypeError: headerbar.pack_start is not a function

Stack trace:
  addMenu@/home/oyedejioyewole/.local/share/gnome-shell/extensions/search-light@icedman.github.com/prefs.js:39:13
  fillPreferencesWindow@/home/oyedejioyewole/.local/share/gnome-shell/extensions/search-light@icedman.github.com/prefs.js:94:10
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

![Screenshot from 2023-12-15 12-46-41](https://github.com/icedman/search-light/assets/57059138/78cec323-ca5e-4b00-b0ff-6941ade1f009)
![Screenshot from 2023-12-15 12-46-51](https://github.com/icedman/search-light/assets/57059138/dda57fc6-bcf7-4583-87fe-b12d31389996)
![Screenshot from 2023-12-15 12-46-55](https://github.com/icedman/search-light/assets/57059138/fe178f48-e1a3-4ab5-a7bf-04c227d52d41)
![Screenshot from 2023-12-15 12-47-13](https://github.com/icedman/search-light/assets/57059138/17f7a1d8-1e57-40ce-9c36-2bba59a1a9cd)

**Comment by OyewoleOyedeji** [comment]
Just by the side, I previously had this plugin working perfectly on the same laptop (the only difference was that it was running GNOME 44, I think)

**Comment by alirezaimi** [comment]
I have same problem .

**Comment by icedman** [comment]
For Gnome 44 and below. Use development branch g44. Or upgrade to Gnome 45 (which seems very stable already)
