### ISSUE TITLE
[Feature Request] Always on top

### ISSUE THREAD

**Issue by ThomasBiede** [icedman/search-light#74]
As the title says a checkbox or configuration option to force the searchlight window to be always on top (e.g. when watching some video in fullscreen) would be nice. Because when watching something in fullscreen and then pressing the keybind to open searchlight, the window opens and you can type in the searchbar just as usual but it is not visible due to the fullscreen video. This could also be a bug, I'm not sure what the expected behavior should be :smile:.

**Comment by icedman** [comment]
Similar solution to this was posted at #77 
I've updated the main branch already while the release at EGO is under review.
