### ISSUE TITLE
[BUG] Doesn't display on top of full screen windows, or maximized window without panel

### ISSUE THREAD

**Issue by RushingAlien** [icedman/search-light#77]
## Description
Hey it seems that search-light does not display on top of full screen windows or maximized windows when panel is not present (i.e on non-primary monitor)

## Reproduce

1. Full screen a window
2. Make sure focus is still on said window
3. try to open search-light
or
1. Mazimize a window when panel is not present
2. Make sure focus is still on said window
3. try to open search-light

# System Details Report
---

## Report details
- **Date generated:**                              2024-03-13 15:44:43

## Hardware Information:
- **Hardware Model:**                              ADVAN 1701
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 7735HS with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            6.02
- **OS Name:**                                     Arch Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.9-2-cachyos

**Comment by RushingAlien** [comment]
Could be an upstream bug since it also happens with : 
- https://github.com/G-dH/window-thumbnails/issues/7
- https://github.com/oae/gnome-shell-pano/issues/263


But i can't say what exactly the bug is, so it can help if you guys can figure out and report if it is upstream

**Comment by RushingAlien** [comment]
It seems that G-dH devs figured it out https://github.com/G-dH/window-thumbnails/issues/7#issuecomment-1995050733

**Comment by icedman** [comment]
I've uploaded the fix to EGO. Full screen popup Works on my setup already.

**Comment by RushingAlien** [comment]
Hi, I can confirm that it works now :D  
Thank you
