### ISSUE TITLE
Keybindings - <Super>Space

### ISSUE THREAD

**Issue by beatboxa** [icedman/search-light#81]
User specified preferences don't appear to take effect.

This includes both custom keybinding and opening the window at the mouse location.

For keybinding: when attempting to assign new keybinding in the preferences, it doesn't appear to "listen" for new keystrokes.

(Also, is there a way to manually assign these?)
I'd like to set it up for a simple:  Super+Space, rather than Ctrl+Super+Space

Tested on Ubuntu 24.04 Beta and Gnome 46; though I noted that others seem to have this on earlier versions
(For example, one user who commented [here](https://extensions.gnome.org/extension/5489/search-light/) is on 22.04 and Gnome 42)

I should note that I've also gone through the similar issues, and reassigned other keybindings in Gnome, such as removal of L-Super for other shortcuts.  I can't even get to the point where I can assign _any_ keybindings.

BTW, thank you for this extension--I've been searching for a more modern replacement for Gnome-Do as I finally upgrade my system.

**Comment by beatboxa** [comment]
For anyone interested, I was able to manually override this for my own system.
To do so, I did the following:

1. Opened the file in a text editor:
~/.local/share/gnome-shell/extensions/search-light@icedman.github.com/extension.js

2. changed the line:
`shortcut = '<Control><Super>Space;`
to
`shortcut = '<Super>Space';`

3. Logged out and logged back in.

Note that this also allows for continuing to use the Left-Super key to bring up Activities within Gnome.

I'm guessing this might not survive an upgrade; and there may be a better way to do this.  And there does still seem to be the underlying bug potentially, of being unable to set preferences within the Search-Light UI on my system.

But for now, this solved my issue.  This is a huge relief, because I use similar functionality all the time on a number of systems (including Mac OS X and Gnome-Do on older Ubuntu systems); and this allows for UX consistency.

I'll leave this open for now just in case there is a bug when it comes to setting & saving preferences; but feel free to close if it's just some quirk with Ubuntu 24.04 beta or my own system configuration.

**Comment by icedman** [comment]
On my own system Arch Linux I cannot grab <Super>Space. These are possible: <Ctrl>Space, <Alt>Space.
I might make the default <Super>Space ... As you've done, but I'm afraid if <Super>Space is still somehow reserved in by the system or by some other app.

**Comment by beatboxa** [comment]
Thanks for the insight.  Using that and some Googling, I think [I found it](https://askubuntu.com/questions/1403503/how-to-make-supershift-or-shiftspace-to-change-input-language-in-ubuntu)!

Using **dconf-editor**, within the following path:
`/ org / gnome / desktop / wm / keybindings `
Change the keybinding for
`switch-input-source` 

By default, this value is set to ['<Super>space', 'XF86Keyboard'].  I changed mine to ['<Super>K', 'XF86Keyboard'] just to test.

This seems to resolve the issue; and it survives a reboot.

**Comment by icedman** [comment]
Thank you for investigating.
