### ISSUE TITLE
[Feature Request] Multi monitor

### ISSUE THREAD

**Issue by nacho-domatix** [icedman/search-light#9]
First of all, thanks for this amazing extension, I've tried over the years many launchers but I wasn't able to find one with the perfect integration with GNOME without 'exiting' my workspace.

That said, I'd like to see this extension working with multi monitor, as I use two screens, and it can be kinda distracting that it always launch on the first one, no matter where I am.

Thanks again and keep doing! :)

**Comment by icedman** [comment]
This feature has recently been added. You can choose a preferred monitor in which to popup the search box.

**Comment by nacho-domatix** [comment]
That's great! But the best option IMHO is to popup in the active monitor, like [ddterm](https://extensions.gnome.org/extension/3780/ddterm/) does.

**Comment by icedman** [comment]
Added a setting to follow where the current cursor.
